# required configuration options
name: HA Fusion Custom
version: 2024.10.0-custom
slug: ha_fusion_custom
description: Dashboard personalizzato con componente Bar universale per sidebar e main
arch:
  - aarch64
  - amd64
  - armv7

# disable the docker default system init
init: false

# homepage of the add-on
url: https://github.com/llingua/ha-fusion-custom

# icon for the menu panel integration
panel_icon: mdi:view-dashboard-variant

# allow non-administration users
panel_admin: false

# security profile
apparmor: true

# ingress feature for the add-on
ingress: true
ingress_stream: true

# enable api to get host port
hassio_api: true

# port to expose, null defaults to disabled
ports:
  8099/tcp: null

# docker hub
image: llingua/addon-ha-fusion-{arch}
